# Generated by Django 4.0.4 on 2025-08-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0003_role_roleaccess_userrole_delete_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleFeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'User Access')])),
                ('access', models.IntegerField(choices=[(1, 'Invite User')])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_role_feature_access', to='v1_profile.role')),
            ],
            options={
                'db_table': 'role_feature_access',
                'unique_together': {('role', 'type', 'access')},
            },
        ),
    ]
