# Generated by Django 4.0.4 on 2025-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0004_alter_questions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='dependency_rule',
            field=models.CharField(
                choices=[('AND', 'AND'), ('OR', 'OR')],
                max_length=3,
                null=True,
                blank=True,
                help_text='Dependency evaluation rule: AND (all must be satisfied) or OR (any must be satisfied). '
                          'If not specified, defaults to AND in client application logic.'
            ),
        ),
    ]
