# Generated by Django 4.0.4 on 2025-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0002_formdata_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDataOptions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('options', models.JSONField(default=None, null=True)),
            ],
            options={
                'db_table': 'view_data_options',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW view_data_options as
                SELECT
                    row_number() over (partition by true) as id,
                    d.parent_id as parent_data_id,
                    tmp.data_id,
                    d.administration_id,
                    d.form_id,
                    to_jsonb(array_agg(
                        concat(tmp.question_id, '||',
                            lower(tmp.option_ids::text))
                    )) as options
                FROM (
                    SELECT
                        a.data_id,
                        a.question_id,
                        a.id as answer_id,
                        jsonb_agg(qo.id) as option_ids
                    FROM answer a
                    LEFT JOIN question q on q.id = a.question_id
                    LEFT JOIN option qo ON qo.question_id = a.question_id 
                        AND qo.value = ANY(SELECT jsonb_array_elements_text(a.options))
                    WHERE (q.type = 5 OR q.type = 6) AND a.options IS NOT NULL
                    GROUP BY a.data_id, a.question_id, a.id
                ) tmp
                LEFT JOIN (
                    SELECT *,
                        ROW_NUMBER() OVER (PARTITION BY parent_id, form_id ORDER BY created DESC) as rn
                    FROM data
                    WHERE parent_id IS NOT NULL
                        AND is_pending = FALSE
                        AND is_draft = FALSE
                ) d ON d.id = tmp.data_id AND d.rn = 1
                LEFT JOIN form f ON f.id = d.form_id
                WHERE f.parent_id IS NOT NULL
                GROUP BY tmp.data_id, d.administration_id, d.form_id, d.parent_id
            """, "DROP MATERIALIZED VIEW view_data_options;")
    ]
