# Generated by Django 4.0.4 on 2025-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
